
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Data
{

using System;
    using System.Collections.Generic;
    
public partial class tbl_SalesDetails
{

    public int Id { get; set; }

    public Nullable<int> SalesId { get; set; }

    public Nullable<int> BookId { get; set; }

    public Nullable<int> OrderQty { get; set; }

    public Nullable<decimal> Price { get; set; }

    public Nullable<int> ReturnQty { get; set; }

}

}
