//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Discount
    {
        public int Id { get; set; }
        public Nullable<int> InvoiceId { get; set; }
        public string PublisherName { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<int> DiscountPercentage { get; set; }
        public Nullable<decimal> DiscountAmount { get; set; }
    }
}
